### ISSUE TITLE
When I landed on free parking it gives me the option to purchase a building

### ISSUE THREAD

**Issue by MohamedZalat** [Joshdowning/Monopoly#2]
The game also throws an exception after giving it a random index.
![image](https://user-images.githubusercontent.com/15681165/139369815-9ef35753-0d95-4034-8851-69fbfab3862d.png)

Note this feature is not even needed for this milestone so I am not deducting marks for it. Just giving you feedback before the milestone where this will be marked.

**Comment by Joshdowning** [comment]
From the rules we referred to it seems like you are allowed to build houses/hotels anywhere on the board no matter what tile you are on as long as it is your turn and you own all the properties of that colour. Should we change it so that you can only build on the property you land on?

**Comment by MohamedZalat** [comment]
Hi Josh,

The title of this issue is misleading, the issue is the out of bound exception not the feature itself!
________________________________

**Comment by Joshdowning** [comment]
thanks, we will have the exception fixed for future milestones
